# Generated by Django 3.1.2 on 2024-05-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='check_out',
        ),
        migrations.AddField(
            model_name='reservation',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='end_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='start_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
