# Generated by Django 3.1.2 on 2024-05-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_auto_20240515_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='reservation',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
