# Generated by Django 3.1.2 on 2024-05-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_auto_20240515_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='tour_included',
            field=models.CharField(default='', max_length=300),
        ),
    ]
