# Generated by Django 3.1.2 on 2024-05-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0007_reservation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='tour',
            name='tour_included',
        ),
        migrations.AddField(
            model_name='tour',
            name='services',
            field=models.ManyToManyField(related_name='tours', to='tour.Service'),
        ),
    ]
