# Generated by Django 3.1.2 on 2024-05-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0009_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='flight/static/tour/photos'),
        ),
    ]
