# Generated by Django 3.1.2 on 2024-05-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_auto_20240507_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dropoff_date',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_date',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
