# Generated by Django 3.1.2 on 2024-05-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_auto_20240507_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref_no',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
